name: filesig Node CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn@latest

      - name: Install Dependencies
        run: yarn

      - name: build types
        run: yarn build:types

      - name: Get sample files
        run: |-
          rm -rf tmp \
            && mkdir -p tmp \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.mp3 https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.mp3 \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.wav https://freewavesamples.com/files/Ensoniq-ZR-76-01-Dope-77.wav \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.ogg https://upload.wikimedia.org/wikipedia/commons/c/c8/Example.ogg \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.doc https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.doc \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.docx https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.docx \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.xls https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.xls \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.xlsx https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.xlsx \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.ppt https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.ppt \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.odt https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.odt \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.pdf https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.pdf \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.rtf https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.rtf \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.mpg https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.mpg \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.flv https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.flv \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.3gp https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.3gp \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.mkv https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.mkv \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.swf https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.swf \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.mp4 https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.mp4 \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.webm https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.webm \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.wmv https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.wmv \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.avi https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.avi \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.mov https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.mov \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.bmp https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.bmp \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.avif http://sample-file.bazadanni.com/download/images/avif/sample.avif \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.webp https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.webp \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.png https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.png \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.jpg https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.jpg \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.tiff https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.tiff \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.gif https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.gif \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.svg https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.svg \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.ico https://github.com/lutfailham96/filesig-test-files/raw/master/sample-0.ico \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.dib https://raw.githubusercontent.com/filestar/File-Type-Sample-Repository/master/dib/sample.dib \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.apk https://raw.githubusercontent.com/appium-boneyard/sample-code/master/sample-code/apps/ContactManager/ContactManager.apk \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.zip https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-zip-file.zip \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.rar https://getsamplefiles.com/download/rar/sample.rar \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.tgz https://getsamplefiles.com/download/gzip/sample.tgz \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.tar https://getsamplefiles.com/download/tar/sample.tar \
            && curl -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Expires: 0" -sLko tmp/sample-0.jar.zip http://www.java2s.com/Code/JarDownload/sample/sample.jar.zip \
            && unzip tmp/sample-0.jar.zip -d tmp \
            && mv tmp/sample.jar tmp/sample-0.jar \
            && rm tmp/sample-0.jar.zip
      - name: Run test
        run: yarn test
